@startuml deployment

node "Application Server" as appServer{
    artifact container {
        artifact "React Application" as ra 
        artifact "Java Spring Application" as jsa
    }
}

node "Device" as user {
    artifact "Browser" as bw
}

node "FileSystem Server" as fServer{
    artifact "FileSystem" as fileSystem
}

node "DB Server" as db {
    artifact "PostGresSQL Server" as PSQL
}
node "Geographical API" as gm

node "Logging System Server" as lss {
    artifact "Logging System" as ls
}


ra -- user : "HTTPs"
ra -- gm : "HTTPs"
db -- jsa : "TCP/IPs"
lss -- jsa : "HTTPs"
fServer -- jsa : "FTPs"
jsa -- ra : "HTTPs"

@enduml